import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
df = pd.read_csv('../results/final/sweep_results.csv')
k3 = df[df['K'] == 3].copy()
labels = k3['threshold'].tolist()
fast_n = k3['fast_n'].tolist()
deep_n = k3['deep_n'].tolist()
x = np.arange(len(labels))
fig, ax = plt.subplots(figsize=(7.5, 4.3))
ax.bar(x, fast_n, label='Routed Fast', color='#55A868')
ax.bar(x, deep_n, bottom=fast_n, label='Routed Deep', color='#C44E52')
ax.set_xticks(x)
ax.set_xticklabels(labels, rotation=20, ha='right')
ax.set_ylabel('Number of queries (of 400)')
ax.set_xlabel('Calibration threshold')
ax.set_title('Fast/Deep routing allocation across the calibration sweep (K=3)')
ax.legend()
fig.tight_layout()
fig.savefig('fig_5_2_calibration_routes.png', dpi=200)
print('saved fig_5_2_calibration_routes.png')
