import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv('../results/final/sweep_results.csv')
k2 = df[df['K'] == 2].sort_values('tau')
k3 = df[df['K'] == 3].sort_values('tau')
fig, ax = plt.subplots(figsize=(7, 4.3))
ax.plot(k2['threshold'], k2['faithfulness'], marker='o', label='K=2', color='#4C72B0')
ax.plot(k3['threshold'], k3['faithfulness'], marker='o', label='K=3', color='#DD8452')
ax.set_xlabel('Calibration threshold')
ax.set_ylabel('Supportedness')
ax.set_title('Supportedness sensitivity for Fast Path K=2 and K=3\nacross the calibration sweep')
ax.legend()
plt.setp(ax.get_xticklabels(), rotation=20, ha='right')
fig.tight_layout()
fig.savefig('fig_5_3_supportedness_sensitivity.png', dpi=200)
print('saved fig_5_3_supportedness_sensitivity.png')
fig, ax = plt.subplots(figsize=(7, 4.3))
ax.plot(k2['threshold'], k2['P95_s'], marker='o', label='K=2', color='#4C72B0')
ax.plot(k3['threshold'], k3['P95_s'], marker='o', label='K=3', color='#DD8452')
ax.set_xlabel('Calibration threshold')
ax.set_ylabel('P95 latency (seconds)')
ax.set_title('P95 latency sensitivity for Fast Path K=2 and K=3\nacross the calibration sweep')
ax.legend()
plt.setp(ax.get_xticklabels(), rotation=20, ha='right')
fig.tight_layout()
fig.savefig('fig_5_4_p95_sensitivity.png', dpi=200)
print('saved fig_5_4_p95_sensitivity.png')
